version: 2
updates:
  - package-ecosystem: docker
    directory: "/kubernetes"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci): "
    open-pull-requests-limit: 10
