version: 2
updates:
  # Update Dockerfile
  - package-ecosystem: "docker"
    directory: "/kubernetes"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci): "
    open-pull-requests-limit: 10
